#!/bin/bash
# ===========================================
# Setup Environment Script
# ===========================================
# This script helps configure environment variables for the project

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
WWW_DIR="$PROJECT_ROOT/www"
ENV_EXAMPLE="$WWW_DIR/.env.example"
ENV_FILE="$WWW_DIR/.env"
ENV_JS="$WWW_DIR/js/core/env.js"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  Coleccion Nuevo Ser - Environment Setup  ${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# Function to check if .env exists
check_env_file() {
    if [ -f "$ENV_FILE" ]; then
        echo -e "${YELLOW}Warning: .env file already exists${NC}"
        read -p "Overwrite? (y/N): " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo -e "${BLUE}Keeping existing .env file${NC}"
            return 1
        fi
    fi
    return 0
}

# Function to copy .env.example to .env
copy_env_example() {
    if [ -f "$ENV_EXAMPLE" ]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        echo -e "${GREEN}Created .env from .env.example${NC}"
    else
        echo -e "${RED}Error: .env.example not found at $ENV_EXAMPLE${NC}"
        exit 1
    fi
}

# Function to validate required variables
validate_env() {
    echo ""
    echo -e "${BLUE}Validating environment variables...${NC}"

    local required_vars=(
        "SUPABASE_URL"
        "SUPABASE_ANON_KEY"
    )

    local optional_vars=(
        "STRIPE_PUBLISHABLE_KEY"
        "RECAPTCHA_SITE_KEY"
        "RESEND_API_KEY"
    )

    local missing=0

    # Source the .env file
    if [ -f "$ENV_FILE" ]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi

    echo ""
    echo -e "${BLUE}Required variables:${NC}"
    for var in "${required_vars[@]}"; do
        if [ -z "${!var}" ] || [[ "${!var}" == *"your-"* ]] || [[ "${!var}" == *"YOUR_"* ]]; then
            echo -e "  ${RED}✗ $var (not configured)${NC}"
            missing=$((missing + 1))
        else
            echo -e "  ${GREEN}✓ $var${NC}"
        fi
    done

    echo ""
    echo -e "${BLUE}Optional variables:${NC}"
    for var in "${optional_vars[@]}"; do
        if [ -z "${!var}" ] || [[ "${!var}" == *"your-"* ]] || [[ "${!var}" == *"YOUR_"* ]]; then
            echo -e "  ${YELLOW}○ $var (not configured)${NC}"
        else
            echo -e "  ${GREEN}✓ $var${NC}"
        fi
    done

    echo ""

    if [ $missing -gt 0 ]; then
        echo -e "${RED}$missing required variable(s) missing!${NC}"
        echo -e "${YELLOW}Please edit $ENV_FILE and configure the required variables.${NC}"
        return 1
    else
        echo -e "${GREEN}All required variables configured!${NC}"
        return 0
    fi
}

# Function to generate env.js for frontend
generate_env_js() {
    echo ""
    echo -e "${BLUE}Generating env.js for frontend...${NC}"

    # Source the .env file
    if [ -f "$ENV_FILE" ]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi

    # Create env.js with only public variables
    cat > "$ENV_JS" << EOF
/**
 * Environment Configuration (Auto-generated)
 * DO NOT EDIT - Generated by scripts/setup-env.sh
 *
 * @generated $(date '+%Y-%m-%d %H:%M:%S')
 */
window.env = {
    // Supabase (public)
    SUPABASE_URL: '${SUPABASE_URL:-}',
    SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY:-}',

    // Stripe (public key only!)
    STRIPE_PUBLISHABLE_KEY: '${STRIPE_PUBLISHABLE_KEY:-}',

    // reCAPTCHA (public key only!)
    RECAPTCHA_SITE_KEY: '${RECAPTCHA_SITE_KEY:-}',

    // App settings
    NODE_ENV: '${NODE_ENV:-development}',
    DEBUG_MODE: ${DEBUG_MODE:-false},
    APP_URL: '${APP_URL:-}'
};

// Freeze to prevent modification
Object.freeze(window.env);

console.log('Environment loaded:', window.env.NODE_ENV);
EOF

    echo -e "${GREEN}Generated $ENV_JS${NC}"
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  setup     Create .env from .env.example and configure"
    echo "  validate  Validate current .env configuration"
    echo "  generate  Generate env.js from .env"
    echo "  all       Run setup, validate, and generate (default)"
    echo "  help      Show this help message"
}

# Main execution
case "${1:-all}" in
    setup)
        if check_env_file; then
            copy_env_example
            echo ""
            echo -e "${YELLOW}Please edit $ENV_FILE with your actual values${NC}"
            echo -e "${YELLOW}Then run: $0 validate${NC}"
        fi
        ;;
    validate)
        validate_env
        ;;
    generate)
        generate_env_js
        ;;
    all)
        if check_env_file; then
            copy_env_example
        fi
        echo ""
        if validate_env; then
            generate_env_js
            echo ""
            echo -e "${GREEN}============================================${NC}"
            echo -e "${GREEN}  Setup Complete!                          ${NC}"
            echo -e "${GREEN}============================================${NC}"
        else
            echo ""
            echo -e "${YELLOW}Complete the .env configuration first${NC}"
        fi
        ;;
    help|--help|-h)
        show_usage
        ;;
    *)
        echo -e "${RED}Unknown command: $1${NC}"
        show_usage
        exit 1
        ;;
esac
